/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aurora: typeof import('./src/components/VueBits/Aurora.vue')['default']
    CountUp: typeof import('./src/components/VueBits/CountUp.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    GradientBox: typeof import('./src/components/VueBits/GradientBox.vue')['default']
    LogoLoop: typeof import('./src/components/VueBits/LogoLoop.vue')['default']
    Plasma: typeof import('./src/components/VueBits/Plasma.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShinyText: typeof import('./src/components/VueBits/ShinyText.vue')['default']
    SplashCursor: typeof import('./src/components/VueBits/SplashCursor.vue')['default']
    SplitText: typeof import('./src/components/VueBits/SplitText.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
  }
}
